spring:
  application:
    name: hystrix-application-client
  redis:
    host: 47.96.21.192 
    database: 0
    #timeout: 0
    port: 6379
    password: crm2019redis
    jedis:
      pool:
        max-idle: 200
        min-idle: 50
        max-active: 100
          

server:
  port: 9002


