

spring:
  application:
    name: test-feign-application-service


server:
  port: 9000
  

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver1:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}    
    